import numpy as np 
import matplotlib.pyplot as plt

'''
uses feature metadata generated by train_cnn_baseline.py, train_cnn_baseline_injected_signal.py, or score_tiles.py to plot
tile mean, std, max, kurtosis, and entropy
'''

# load features
FEATURES_PATH = "../data/features.npy" 
OUTPUT_PATH = "../figures/feature_distributions.png" 
features = np.load(FEATURES_PATH, allow_pickle=True)

# extract arrays
means = np.array([f["mean"] for f in features]) 
stds = np.array([f["std"] for f in features]) 
max_vals = np.array([f["max"] for f in features]) 
kurt = np.array([f["kurtosis"] for f in features]) 
ent = np.array([f["entropy"] for f in features])

# plot
fig, axs = plt.subplots(2, 3, figsize=(12, 8)) 
axs = axs.flatten() 
axs[0].hist(means, bins=50) 
axs[0].set_title("Mean Power") 
axs[1].hist(stds, bins=50) 
axs[1].set_title("Standard Deviation") 
axs[2].hist(max_vals, bins=50) 
axs[2].set_title("Maximum Power") 
axs[3].hist(kurt, bins=50) 
axs[3].set_title("Kurtosis") 
axs[4].hist(ent, bins=50) 
axs[4].set_title("Spectral Entropy")
axs[5].scatter(stds, max_vals, s=3, alpha=0.5)
axs[5].set_xlabel("Std")
axs[5].set_ylabel("Max")
axs[5].set_title("Std vs Max Power")

for ax in axs: 
 ax.grid(alpha=0.3) 
plt.suptitle("Feature Distributions for Waterfall Tiles", fontsize=14) 
plt.tight_layout(rect=[0, 0, 1, 0.96]) 
plt.savefig(OUTPUT_PATH, dpi=150) 
plt.close() 
print(f"Saved feature distribution plot to {OUTPUT_PATH}")
