import json
import matplotlib.pyplot as plt

'''
Reads in scored_tiles_inj.json generated by score_tiles.py and plots features vs. CNN score with injected signals
highlighted.  This can inform fine-tuning of LLMs and further evaluate the performance of the trained CNN.

'''

# config

INPUT_JSON = "../outputs/scored_tiles_inj.json"
OUTPUT_PATH_feat = "../figures/scored_features_"
OUTPUT_PATH_ek = "../figures/entropy_kurtosis.png"

# get_tiles

with open(INPUT_JSON) as f:
    data = json.load(f)

inj = [d for d in data if d["injected"]]
bg  = [d for d in data if not d["injected"]]

def feat(arr, key):
    return [d["features"][key] for d in arr]

def scores(arr):
    return [d["cnn_score"] for d in arr]

print(f"Total tiles: {len(data)}")
print(f"Injected tiles: {len(inj)}")

# plot feature versus llm score

features = ["mean", "std", "max", "entropy", "kurtosis"]

for f in features:
    plt.figure()
    plt.scatter(
        scores(bg),
        feat(bg, f),
        alpha=0.5,
        label="Not injected",
    )
    plt.scatter(
        scores(inj),
        feat(inj, f),
        alpha=0.9,
        label="Injected",
    )
    plt.xlabel("CNN anomaly score")
    plt.ylabel(f)
    plt.title(f"{f} vs CNN score")
    plt.legend()
    plt.savefig(OUTPUT_PATH_feat+str(f)+".png")
    plt.close()

# plot Entropy vs Kurtosis 

non_entropy = [d["features"]["entropy"] for d in bg]
non_kurt = [d["features"]["kurtosis"] for d in bg]

inj_entropy = [d["features"]["entropy"] for d in inj]
inj_kurt = [d["features"]["kurtosis"] for d in inj]

plt.figure()
plt.scatter(non_entropy, non_kurt, label="Not injected")
plt.scatter(inj_entropy, inj_kurt, label="Injected")
plt.xlabel("Entropy")
plt.ylabel("Kurtosis")
plt.title("Entropy vs Kurtosis")
plt.legend()
plt.savefig(OUTPUT_PATH_ek)
plt.close()
